In [1]:
#prepare a L1 and L2 model for prediction of house prices

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [7]:
df = pd.read_csv("Housing.csv")

In [ ]:
df.info()

In [ ]:
df.head()

In [13]:
df.shape

(20640, 10)

In [ ]:
df["ocean_proximity"]=df.groupby("ocean_proximity")["median_house_value"].transform("mean")
df.info()

In [ ]:
#normalisation(scaling)
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df1 = pd.DataFrame(scaler.fit_transform(df),columns = df.columns)

In [25]:
df1.fillna(999,inplace = True)
#inplace true makes the changes permanent 

In [29]:
y = df1["median_house_value"]
x = df1.drop("median_house_value",axis = 1)

In [31]:
x.shape , y.shape

((20640, 9), (20640,))

In [ ]:
df1.info()

In [35]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3 , random_state = 1)

In [37]:
x_train.shape,x_test.shape

((14448, 9), (6192, 9))

In [39]:
linear_model = LinearRegression()
lasso_model = Lasso(alpha = 0.1)
ridge_model = Ridge(alpha = 0.1)

In [41]:
#alpha is the regularisation parameter which we are adding as an Error term to our model
#we are not taking the errors added in the feature we are only taking Regularisationl

In [43]:
linear_model.fit(x_train,y_train)

LinearRegression()

In [45]:
lasso_model.fit(x_train,y_train)

Lasso(alpha=0.1)

In [47]:
ridge_model.fit(x_train,y_train)

Ridge(alpha=0.1)

In [49]:
linear_model.coef_,lasso_model.coef_,ridge_model.coef_

(array([-5.21369632e-01, -4.80885402e-01,  1.05448058e-01, -9.95155295e-02,
         9.05811317e-07, -2.96900236e+00,  1.71684723e+00,  1.14140894e+00,
         1.78608947e-01]),
 array([-0., -0.,  0.,  0.,  0., -0.,  0.,  0.,  0.]),
 array([-5.19071574e-01, -4.77794156e-01,  1.05589015e-01, -8.48795182e-02,
         8.27450951e-07, -2.83592891e+00,  1.64191665e+00,  1.13973254e+00,
         1.80420220e-01]))

In [53]:
linear_model.intercept_,lasso_model.intercept_,ridge_model.intercept_

(0.40752917375286146, 0.3972234099154518, 0.40501227584561317)

In [51]:
linear_model.score(x_test,y_test),lasso_model.score(x_test,y_test),ridge_model.score(x_test,y_test)

(0.636316988586481, -0.0005372966032284321, 0.636010311671446)

In [57]:
linear_train_mse = mean_squared_error(y_train,linear_model.predict(x_train))
linear_train_mse

0.02023851649428413

In [59]:
linear_test_mse = mean_squared_error(y_test,linear_model.predict(x_test))
linear_test_mse

0.020326239023693262

In [61]:
lasso_train_mse = mean_squared_error(y_train,lasso_model.predict(x_train))
lasso_train_mse

0.056905352645749696

In [65]:
lasso_test_mse = mean_squared_error(y_test,lasso_model.predict(x_test))
lasso_test_mse

0.05592001717053842

In [67]:
ridge_train_mse = mean_squared_error(y_train,ridge_model.predict(x_train))
ridge_train_mse

0.020242018001132046

In [69]:
ridge_test_mse = mean_squared_error(y_test,ridge_model.predict(x_test))
ridge_test_mse

0.020343379192693252